version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: minha512/ai-doctor_frontend:latest
    container_name: ai-doctor_frontend_service
    restart: unless-stopped
    volumes:
      - ./frontend:/web
      - /web/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
