version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: minha512/ai-doctor_backend:latest
    container_name: ai-doctor_backend_service
    restart: unless-stopped
    volumes:
      - ./backend:/back
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    #   - NVIDIA_VISIBLE_DEVICES=0
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: minha512/ai-doctor_frontend:latest
    container_name: ai-doctor_frontend_service
    restart: unless-stopped
    volumes:
      - ./frontend:/web
      - /web/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
